version: "3.5"
services:
  # Orion is the context broker
  orion:
    image: fiware/orion:2.4.0
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "1026:1026" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  
  # Databases
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" # localhost:27017 # localhost:27017
    networks:
      - default
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`; 
        mongo --quiet $host/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1

  postgres-db:
    image: postgres:latest
    hostname: postgres-db
    container_name: db-postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pg-admin
    container_name: pgadmin
    expose:
      - "3100"
    ports:
      - "3100:80"
    networks:
      - default
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"
      - "PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True"
      - "PGADMIN_CONFIG_LOGIN_BANNER='Authorised users only!'"
      - "PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10"

  grafana:
    hostname: grafana
    container_name: grafana_inspira
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - default
    expose:
      - "3000"
    volumes:
      - grafana-volume:/var/lib/grafana/data

networks:
  default:
    ipam:
      config:
        - subnet: 172.19.100.0/24

volumes:
  mongo-db: ~
  postgres-db: ~
  grafana-volume: ~