version: '3.1'
services:

  draco:
      image: ging/fiware-draco:1.1.0
      container_name: draco2
      depends_on:
          - postgres-db
      environment:
          - NIFI_WEB_HTTP_PORT=9090
      ports:
          - "9090:9090"
          - "5050:5050"
      healthcheck:
          test: curl --fail -s http://localhost:9090/nifi-api/system-diagnostics || exit 1

  postgres-db:
      image: postgres:latest
      hostname: postgres-db
      container_name: db-postgres
      expose:
          - "5432"
      ports:
          - "5432:5432"
      networks:
          - default
      environment:
          - "POSTGRES_PASSWORD=password"
          - "POSTGRES_USER=postgres"
          - "POSTGRES_DB=postgres"